[package]
name = "middle-sock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
dhcproto = "0.11.0"
env_logger = "0.10.1"
futures = "0.3.30"
log = "0.4.20"
rtnetlink = "0.14.0"
